version: '3.7'

services:

  flask:
    container_name: slue_backend
    build: ./backend
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  # angular:
  #   container_name: slue_frontend
  #   build: ./frontend
  #   command: ng serve --host 0.0.0.0 --disableHostCheck
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./frontend:/app

  alpinejs:
    container_name: slue_frontend
    build: ./frontend-alpinejs
    command: npx lite-server
    ports:
      - 3000:3000
    volumes:
      - ./frontend-alpinejs:/app
