version: '3.7'

services:

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-prod
    ports:
      - '8888:80'

  # flask:
  #   build: ./backend
  #   container_name: flask-prod
  #   restart: always
  #   environment:
  #     - MONGO_URI=mongodb://mesinesp:mesinesp@bsccnio01.bsc.es:27017/BvSalud
  #   command: uwsgi app.ini

  flask:
    build: ./backend
    container_name: flask
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
