version: '3.7'

services:

  # DEVELOPMENT BACKEND
  flask:
    build: ./backend
    container_name: slue_backend
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  # PRODUCTION BACKEND
  # flask:
  #   build: ./backend
  #   container_name: flask-prod
  #   restart: always
  #   environment:
  #     - MONGO_URI=mongodb://mesinesp:mesinesp@bsccnio01.bsc.es:27017/BvSalud
  #   command: uwsgi app.ini

  # angular:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   container_name: slue_frontend
  #   ports:
  #     - '8888:80'

  alpinejs:
    build:
      context: ./frontend-alpinejs
      dockerfile: Dockerfile.prod
    container_name: slue_frontend
    ports:
      - '8888:80'
