version: '3.7'

services:

  flask:
    container_name: flask
    build: ./backend
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
  
  angular:
    container_name: angular
    build: ./frontend
    command: ng serve --host 0.0.0.0 --disableHostCheck
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
