version: '3.7'

services:

  flask:
    build: ./backend
    container_name: flask
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  vanilla:
    build: ./frontend-vanilla
    container_name: vanilla
    command: live-server --port=8888
    ports:
      - 8888:8888
    volumes:
      - ./frontend-vanilla:/app
