version: '3.7'
services:
  flask:
    build: ./backend
    container_name: slue_backend
    restart: always
    command: uwsgi app.ini
  alpinejs:
    build:
      context: ./frontend-alpinejs
      dockerfile: Dockerfile.prod
    container_name: slue_frontend
    ports:
      - '8888:80'

  # angular:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #   container_name: slue_frontend
  #   ports:
  #     - '8888:80'
