version: '3.7'

services:

  # flask-prod:
  #   container_name: flask-prod
  #   build: ./backend
  #   restart: always
  #   environment:
  #     - MONGO_URI=mongodb://mesinesp:mesinesp@bsccnio01.bsc.es:27017/BvSalud
  #   command: uwsgi app.ini

  flask-dev:
    build: ./backend
    container_name: flask-dev
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  angular-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-prod
    ports:
      - '8888:80'
