version: '3.7'

services:

  flask:
    build: ./backend
    container_name: flask
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  angular:
    build: ./frontend
    container_name: angular
    command: ng serve --host 0.0.0.0 --disableHostCheck
    ports:
      - 8888:4200
    volumes:
      - ./frontend:/app
