FROM nginx:1.17-alpine

# Remove the default.conf and copy your nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
COPY index.html /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
